[project]
name = "pytester"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pytester = "pytester:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
